services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: nathanjohn
      POSTGRES_PASSWORD: DddtpZW7PR7YCPCe
      POSTGRES_DB: ProjectManagementDatabase
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:9.8
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nj@njtd.xyz
      PGADMIN_DEFAULT_PASSWORD: brother1
